/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.romashov.ash.application.data;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
