name: CI

on:
  push:
    paths:
      # '*' matches any character except '/'
      - .github/workflows/ci.yaml
      - build.gradle
      - settings.gradle
      - 'application/bot/src/**'
      - 'application/bot/build.gradle'
      - 'application/data/src/**'
      - 'application/data/build.gradle'
      - 'tests/e2e/src/**'
      - 'tests/e2e/build.gradle'
      - 'tests/integration/src/**'
      - 'tests/integration/build.gradle'
  pull_request:
    paths:
      # '*' matches any character except '/'
      - .github/workflows/ci.yaml
      - build.gradle
      - settings.gradle
      - 'application/bot/src/**'
      - 'application/bot/build.gradle'
      - 'application/data/src/**'
      - 'application/data/build.gradle'
      - 'tests/e2e/src/**'
      - 'tests/e2e/build.gradle'
      - 'tests/integration/src/**'
      - 'tests/integration/build.gradle'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Set up Gradle 5.6.4
        run: |
          mkdir /opt/gradle
          wget https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
          unzip -d /opt/gradle gradle-5.6.4-bin.zip
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-executable: /opt/gradle/gradle-5.6.4/bin/gradle
          arguments: --project-dir application/bot build
