name: Wakeup

on:
  schedule:
    - cron: '*/20 * * * *' # Runs every 5 mins

jobs:
  build-pages:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl https://scoteam-bot.herokuapp.com
